version: 2.1
executors:
  default:
    docker:
      - image: circleci/ruby:2.5

jobs: # ステップの集合
  build: # Workflows を使用しない実行では、エントリポイントとして `build` ジョブが必要
    docker: # Docker でステップを実行します
      - image: circleci/openjdk:8-jdk-browsers # このイメージをすべての `steps` が実行されるプライマリコンテナとして使用します
    steps: # 実行可能コマンドの集合
      - checkout
      - run: ./gradlew build
  test:
    docker: # Docker でステップを実行します
      - image: circleci/openjdk:8-jdk-browsers # このイメージをすべての `steps` が実行されるプライマリコンテナとして使用します
    steps:
      - checkout
      - run: ./gradlew test
#jobs:
#  - build:
#      steps:
#          - checkout
#  - test:
#      executor: default
#      steps:
#        - checkout
#        - run: ./gradlew test

workflows:
  commit:
    jobs:
      - test