version: 2.1
executors:
  default:
    docker:
      - image: circleci/ruby:2.5
#commands:
#  test:
#    description: "test"
#    steps:
#      - run: ./gradlew test

jobs:
  build:
#    docker:
#      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: ./gradlew build
  test:
#    docker:
#      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: ./gradlew test
#jobs:
#  - build:
#      steps:
#          - checkout
#  - test:
#      executor: default
#      steps:
#        - checkout
#        - run: ./gradlew test

workflows:
  commit:
    jobs:
      - test